theme: jekyll-theme-slate
title: Engineering Portfolio
description: Aerospace & Mechanical Engineering
show_downloads: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
